Repository react-bratus/react-bratus, pull requests merged in 2022-04, with the labels that each got.

#58 Evgenios/feature/proportional size on demand
  packages/bratus-app/src/App.js
  packages/bratus-app/src/components/ComponentDetails/ComponentDetails.jsx
  packages/bratus-app/src/components/ComponentNode/ComponentNode.jsx
  packages/bratus-app/src/components/ComponentNode/ComponentNode.sc.js
  packages/bratus-app/src/components/ComponentTree/private/LayoutButtons.jsx
  packages/bratus-app/src/components/NavigationPanel/NavigationPanel.jsx
  packages/bratus-app/src/index.js
  packages/bratus-app/src/providers/ComponentBackgroundProvider.js
  packages/bratus-app/src/utils/functions/graphUtils.js
Labels: enhancement

#59 Piotrek/bugfix/conditional-rendering
  packages/bratus-app/src/utils/functions/nodes-and-edges.js
  packages/bratus-cli/src/parser/ASTParser.ts
  packages/bratus-cli/src/parser/Builder/JSXElement.ts
  packages/bratus-cli/src/parser/Graph/Edge.ts
  packages/bratus-cli/src/parser/Graph/Graph.ts
Labels: bugfix, Work needed later

#60 Evgenios/feature/customizing sidebar
  packages/bratus-app/src/components/NavigationPanel/NavigationPanel.jsx
  packages/bratus-app/src/components/NavigationPanel/NavigationPanel.sc.js
  packages/bratus-app/src/components/NavigationPanel/private/ActionButtons/ActionButtons.sc.js
  packages/bratus-app/src/components/NavigationPanel/private/ActionButtons/NavigationGitHubActions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/ActionButtons/NavigationPrimaryActions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/NavigationActionButtons/NavigationActionButtons.jsx
  packages/bratus-app/src/components/NavigationPanel/private/NavigationActionButtons/NavigationActionButtons.sc.js
  packages/bratus-app/src/components/NavigationPanel/private/NavigationSection/NavigationSection.jsx
  packages/bratus-app/src/components/NavigationPanel/private/NavigationSection/NavigationSection.sc.js
  packages/bratus-app/src/components/NavigationPanel/private/SectionTitle/SectionTitle.jsx
  packages/bratus-app/src/components/NavigationPanel/private/SectionTitle/SectionTitle.sc.js
  packages/bratus-app/src/components/NavigationPanel/private/SubMenuSections/NavNodeVisualizationOptions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/SubMenuSections/NavSearchComponent.jsx
  packages/bratus-app/src/utils/tokens/constants.js
  packages/bratus-app/src/utils/tokens/units.js
Labels: enhancement

#68 Implementing prefered vertical layout option
  packages/bratus-app/src/App.js
  packages/bratus-app/src/components/DefaultLayoutPage/DefaultLayout.jsx
  packages/bratus-app/src/components/HelpPanel/HelpPanel.jsx
Labels: enhancement

#75 Displaying ... when comp name more than 13 chars
  packages/bratus-app/src/components/ComponentNode/ComponentNode.jsx
  packages/bratus-app/src/utils/constants/units.js
Labels: enhancement

#74 Replacing strings with constants
  packages/bratus-app/src/components/ComponentDetails/ComponentDetails.jsx
  packages/bratus-app/src/components/ComponentNode/ComponentNode.jsx
  packages/bratus-app/src/components/ComponentNode/ComponentNode.sc.js
  packages/bratus-app/src/components/ComponentTree/private/LayoutButtons.jsx
  packages/bratus-app/src/components/DefaultLayoutPage/DefaultLayout.jsx
  packages/bratus-app/src/components/HelpPanel/HelpPanel.tsx
  packages/bratus-app/src/components/HelpPanel/private/EdgesSection.tsx
  packages/bratus-app/src/components/HelpPanel/private/NodesSection.tsx
  packages/bratus-app/src/components/NavigationPanel/NavigationPanel.jsx
  packages/bratus-app/src/components/NavigationPanel/private/ActionButtons/NavigationGitHubActions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/ActionButtons/NavigationPrimaryActions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/SubMenuSections/NavNodeVisualizationOptions.jsx
  packages/bratus-app/src/contexts/ComponentBackgroundContext.js
  packages/bratus-app/src/providers/ComponentBackgroundProvider.js
  packages/bratus-app/src/utils/constants/constants.js
  packages/bratus-app/src/utils/functions/graphUtils.js
Labels: Premium cleaning services

#77 Pushing docs
  docs/publish-on-npm.md
Labels: documentation

#78 Evgenios/feature/adding comments to the app
  packages/bratus-app/src/App.js
  packages/bratus-app/src/components/ComponentDetails/ComponentDetails.jsx
  packages/bratus-app/src/components/ComponentNode/ComponentNode.jsx
  packages/bratus-app/src/components/ComponentNode/ComponentNode.sc.js
  packages/bratus-app/src/components/ComponentTree/ComponentTree.jsx
  packages/bratus-app/src/components/ComponentTree/ComponentTree.sc.js
  packages/bratus-app/src/components/ComponentTree/private/LayoutButtons.jsx
  packages/bratus-app/src/components/DefaultLayoutPage/DefaultLayout.jsx
  packages/bratus-app/src/components/DefaultLayoutPage/DefaultLayout.sc.js
  packages/bratus-app/src/components/HelpPanel/HelpPanel.sc.js
  packages/bratus-app/src/components/HelpPanel/private/PreferencesSection.tsx
  packages/bratus-app/src/components/NavigationPanel/NavigationPanel.jsx
  packages/bratus-app/src/components/NavigationPanel/private/ActionButtons/NavigationGitHubActions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/ActionButtons/NavigationPrimaryActions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/SubMenuSections/NavNodeVisualizationOptions.jsx
  packages/bratus-app/src/components/NavigationPanel/private/SubMenuSections/NavSearchComponent.jsx
  packages/bratus-app/src/hooks/useStickyState.js
  packages/bratus-app/src/utils/constants/units.js
  packages/bratus-app/src/utils/functions/graphUtils.js
  packages/bratus-app/src/utils/functions/nodes-and-edges.js
  packages/bratus-app/src/utils/functions/rgbaToHex.js
Labels: documentation

#80 Evgenios/feature/deleting unused functionality
  packages/bratus-app/.linguirc
  packages/bratus-app/package.json
  packages/bratus-app/src/App.js
  packages/bratus-app/src/components/ComponentTree/private/LayoutButtons.jsx
  packages/bratus-app/src/components/DefaultLayoutPage/DefaultLayout.jsx
  packages/bratus-app/src/hooks/index.js
  packages/bratus-app/src/hooks/useLocale.js
  packages/bratus-app/src/index.js
  packages/bratus-app/src/locales/da/da.mo
  packages/bratus-app/src/locales/da/da.po
  packages/bratus-app/src/locales/da/messages.js
  packages/bratus-app/src/locales/da/messages.po
  packages/bratus-app/src/locales/en/messages.js
  packages/bratus-app/src/locales/en/messages.po
  packages/bratus-app/src/providers/I18nWatchLocaleProvider.js
  packages/bratus-app/src/providers/Providers.tsx
  packages/bratus-app/src/providers/ThemeProvider.js
  packages/bratus-app/src/utils/functions/index.js
  packages/bratus-app/src/utils/functions/locale.js
Labels: Premium cleaning services
